import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

import { Playfair_Display, Libre_Baskerville, DM_Sans } from "next/font/google";
import "./globals.css";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const regale = localFont({
  src: [
    {
      path: "../public/fonts/Regale-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-regale",
  display: "swap",
});

const butler = Libre_Baskerville({
  variable: "--font-butler",
  subsets: ["latin"],
});

const satoshi = DM_Sans({
  variable: "--font-satoshi",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
           ${playfair.className}

          ${regale.variable}
          ${butler.variable}
          ${satoshi.variable}
        
          antialiased



          bg-red-500
        `}
      >
        {children}
      </body>
    </html>
  );
}
